### ISSUE TITLE
能实现自动签到？

### ISSUE THREAD

**Issue by FIlN** [iozephyr/Get_UJN_Lib_Seat#10]

**Comment by hephyr** [comment]
签到要求请求签到API的设备必须在可签到的 IP 段内

**Comment by SnowClick** [comment]
如果我在图书馆放一个手机或者树莓派之类的。。

**Comment by hephyr** [comment]
这是一个解决办法

**Comment by FIlN** [comment]
但是我听说有人只用代码实现了伪装图书馆签到。这什么鬼？

**Comment by hephyr** [comment]
> 但是我听说有人只用代码实现了伪装图书馆签到。这什么鬼？

据我了解，图书馆服务器判断的是 IP 层的 IP 地址，技术上修改 IP 层完成 TCP 三次握手不太可能。

**Comment by forhuan** [comment]
> 如果我在图书馆放一个手机或者树莓派之类的。。

图书馆的WiFi不是一般的差

**Comment by hephyr** [comment]
可以实现签到功能了
