### ISSUE TITLE
预约时间点问题

### ISSUE THREAD

**Issue by kuiv587** [iozephyr/Get_UJN_Lib_Seat#13]
大神你好，最近每次预约成功或失败反馈的时间在5.01时间，是因为图书馆服务器在5.00时过于忙碌导致的吗…

**Comment by kuiv587** [comment]
有同学在5.00多几秒预约成功的情况…

**Comment by hephyr** [comment]
很大可能性是这样，你记录一下你获取 dates() 能够预约的时间。比对一下两者差了多少时间，就能知道具体是服务器开的晚还是服务器网络拥堵。

**Comment by kuiv587** [comment]
谢谢，明天记录下

**Comment by kuiv587** [comment]
大神，获取date ()时，会不会也受到网络延迟的影响？

**Comment by hephyr** [comment]
会的

**Comment by kuiv587** [comment]
大神，我发现确实获取date()与预约时间存在网络延迟， 同时发现了新问题。。 偶尔运行时会产生requests.exceptions.ConnectionError: (‘Connection aborted.’, RemoteDisconnected(‘Remote end closed connection without response’,))错误 ，是因为服务器那边的问题吗

**Comment by hephyr** [comment]
如果你这边同时并发很多预约也会导致延迟

**Comment by kuiv587** [comment]
大神晚安 我想并行运行多个定时任务 来多个同时预约 但是有时会产生错误。。 不知道应该怎么多进程。。

**Comment by hephyr** [comment]
从维护管理的角度来说不建议这么做，建议是一个脚本采用多进程的方式。

**Comment by lhsjohn** [comment]
想问一下有关crontab 的事情,设置好定时后电脑要求是开机状态?

**Comment by hephyr** [comment]
你想让电脑在关机状态下做点事情？

**Comment by lhsjohn** [comment]
如果有个代理服务器就很赞了🐶

**Comment by hephyr** [comment]
可以选择自己买云服务器
