### ISSUE TITLE
hello,could you tell me how you get the api of seat.ujn.edu.cn

### ISSUE THREAD

**Issue by wrmtl** [iozephyr/Get_UJN_Lib_Seat#15]

**Comment by wrmtl** [comment]
I have used fillder to find the posibility apis of that net,but I did not find any apis liked those in code.
I really want to know how you get the idea.
Thanks for your help.

**Comment by hephyr** [comment]
I think you got the website api.  I got those from the APP.  It may be not same.

**Comment by wrmtl** [comment]
Thank you very much for your generosity. Your ideas inspired me.：）
