### ISSUE TITLE
返回message:"Invalid Request"的问题

### ISSUE THREAD

**Issue by Rock-L21** [iozephyr/Get_UJN_Lib_Seat#20]
各种参数都正常，也登陆上去了，但是没有预约成功。为什么返回以下这个message。
{
  "status": "fail",
  "code": "20",
  "message": "Invalid Request",
  "data": null
}

**Comment by ygwlgGiao** [comment]
哦买噶，我的也是555555555555555555

**Comment by kaiyuner** [comment]
+1

**Comment by ygwlgGiao** [comment]
可以签到，哈哈

**Comment by kaiyuner** [comment]
你可以了？

**Comment by ygwlgGiao** [comment]
不可以约座，但是其他的功能貌似都没问题，所以拿来签到是可以的啊

**Comment by kaiyuner** [comment]
主要还是约座啊，签到手动就可以了

**Comment by ygwlgGiao** [comment]
咱俩想的正好相反，我是觉得抢座手动就可以了，主要是签到太麻烦，每次都去晚了

**Comment by kaiyuner** [comment]
那你还是能抢到，像我这种手拙的，还是抢不到

**Comment by ygwlgGiao** [comment]
我在四楼，每天七点半起来约座  :D

**Comment by kaiyuner** [comment]
六楼，七点都抢不到，瑟瑟发抖

**Comment by ygwlgGiao** [comment]
这么惨吗，APP升级之后就再也没有过六楼，因为七点起不来

**Comment by kaiyuner** [comment]
手残党不配在六楼

**Comment by kuiv587** [comment]
签到需要内网才能用....

**Comment by kaiyuner** [comment]
手机扔图书馆

**Comment by ygwlgGiao** [comment]
嗯，我知道，我打算放个破手机

**Comment by hephyr** [comment]
应该是由于 freeBook 接口 `transfer-encoding` 是 `chunked`，然而我目前还没有找到 使用 `requests` POST chunked 数据的办法。

**Comment by iamwwc** [comment]
https://github.com/iozephyr/UJN-Lib-Seat-API/blob/be22e4611f0fe72f3008a59a3691d57da3ac9628/libapi/leoapi.py#L54

token要放到querystring  ?token=xxxxx

新版就改了个这个

**Comment by hephyr** [comment]
抓包请求
![Jietu20190523-110354@2x](https://user-images.githubusercontent.com/8982774/58222984-7f66b480-7d4a-11e9-8e5f-5c0cc5fb7ebe.jpg)

Python 模拟请求
![Jietu20190523-110343@2x](https://user-images.githubusercontent.com/8982774/58223009-8b527680-7d4a-11e9-9943-f7f131850eda.jpg)

**Comment by hephyr** [comment]
> https://github.com/iozephyr/UJN-Lib-Seat-API/blob/be22e4611f0fe72f3008a59a3691d57da3ac9628/libapi/leoapi.py#L54
> 
> token要放到querystring ?token=xxxxx

已经放进去了但还是不可以，目前怀疑是 chunked post 的原因。

**Comment by iamwwc** [comment]
![image](https://user-images.githubusercontent.com/24750337/58223873-ffdae480-7d4d-11e9-8104-3354540b5483.png)
我这没问题
你可能遗漏了什么（token还有效吗？）

**Comment by hephyr** [comment]
> ![image](https://user-images.githubusercontent.com/24750337/58223873-ffdae480-7d4d-11e9-8104-3354540b5483.png)
> 我这没问题
> 你可能遗漏了什么（token还有效吗？）

我写的 HMAC 的原因，有个疑问是你在[这里](https://github.com/iozephyr/UJN-Lib-Seat-API/issues/19#issuecomment-493819900)说使用 2018 年的时间戳也有效是什么意思？post 的时间戳不是用来验证 hmac 的吗，为什么还可以更改？

**Comment by hephyr** [comment]
他们对 GET 和 POST 方法使用了不同的校验，新的[commit](https://github.com/iozephyr/UJN-Lib-Seat-API/commit/9c4484c498898f9d516e5f0f6ff9b09e57dc19d6#diff-1d45314d259150e34d2f6e7317480e1aR60)测试可用。

**Comment by iamwwc** [comment]
我说的有歧义

id，date，hmac这三个头是一起的，也就是修改手机时间抓包然后抓到的这三个头也是可以用的，我想说的是服务器没有对时间戳时间的范围进行限制，如果想要更改时间戳，那么连带着剩余的两个头y也需要改

**Comment by hephyr** [comment]
签到功能可以正常使用。
