### ISSUE TITLE
服务器上运行出现由于连接方在一段时间没有正确答复或连接

### ISSUE THREAD

**Issue by kuiv587** [iozephyr/Get_UJN_Lib_Seat#21]
-在腾讯云上运行出现了问题，不知道是不是腾讯云的原因。timeouterror「win error10060」由于连接方在一段时间没有正确答复或连接的主机没有反应，尝试连接失败

**Comment by hephyr** [comment]
什么提示的？是运行代码还是什么？

**Comment by kuiv587** [comment]
![IMG_0089](https://user-images.githubusercontent.com/36727593/58241306-4ac12000-7d7f-11e9-908a-882d8bba3ba7.jpeg)

**Comment by hephyr** [comment]
排除网络问题的话，有很大可能是你的代码问题。

**Comment by kuiv587** [comment]
同样的代码可以在笔记本上运行…

**Comment by qq1554135900** [comment]
我也有，我在图书馆在笔记本上可以，家里的网，华为云服务器都不行

**Comment by medtutu** [comment]
我也有这个问题，我在图书馆在笔记本上可以，家里的网，华为云服务器都不行

**Comment by medtutu** [comment]
挂济大的vpn可解决

**Comment by GhostLee** [comment]
南苑宿舍区移动网无法访问

**Comment by hephyr** [comment]
可以先写个程序测试一下，比如
``` Python
import requests
r = requests.get("https://202.194.76.30:8443", verify=False, timeout=5)
```

**Comment by medtutu** [comment]
确定是网络的问题，有些网络环境下无法访问，挂济大的vpn就没问题了。
