### ISSUE TITLE
这不清真

### ISSUE THREAD

**Issue by forhuan** [iozephyr/Get_UJN_Lib_Seat#8]
https://github.com/iozephyr/UJN-Lib-Seat-API/blob/f762c34c99399ba6bfddcdf979bd74a68d4f4abe/libapi/api.py#L53

**Comment by hephyr** [comment]
你以为这是我的 ？🙃

**Comment by forhuan** [comment]
看名字就不像是你的

**Comment by forhuan** [comment]
有tg么

**Comment by hephyr** [comment]
https://t.me/Zephyr_Hsu
